#!/usr/bin/env python

"""
This file is part of qnotero.

qnotero is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

qnotero is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with qnotero.  If not, see <http://www.gnu.org/licenses/>.
"""

if __name__ == "__main__":

	import sys
	from libqnotero.qnotero import Qnotero
	from PyQt4.QtGui import QApplication
	
	reset = "--reset" in sys.argv
		
	app = QApplication(sys.argv)
	app.setQuitOnLastWindowClosed(False)
	qnotero = Qnotero(systray=True, debug=True, reset=reset)		
	sys.exit(app.exec_())